// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Email List</title><link rel=\"stylesheet\" href=\"/static/css/modern-normalize.css\"><link rel=\"stylesheet\" href=\"/static/css/style.css\"><script src=\"/static/js/main.js\"></script><script src=\"/static/js/alpine.min.js\"></script></head><body x-init=\"loadStylesheets()\"><section class=\"container section login\"><form class=\"login__form\" id=\"loginForm\"><img alt=\"jmemail\" title=\"jmemail\"><h1 class=\"login__h1\">Sign in</h1><h6 class=\"login__h6\">to continue to jmemail</h6><div><input type=\"email\" id=\"emailid\" name=\"emailid\" required class=\"email__input\" placeholder=\"Email, phone, or Skype\" autocomplete=\"username\"><div class=\"error__message\" id=\"emailError\">Enter a valid email address.</div></div><div class=\"form__group form__submit\"><button type=\"submit\" class=\"next__button\" id=\"nextButton\">Next</button></div><div class=\"form__options\"><label class=\"form__checkbox\"><input type=\"checkbox\" id=\"staySignedIn\"> <span>Keep me signed in</span></label></div><div class=\"form__options\" style=\"justify-content: flex-start; margin-top: 16px;\"><a href=\"#\" class=\"form__link\">Can't access your account?</a></div><div class=\"form__options\" style=\"justify-content: flex-start; margin-top: 8px;\"><a href=\"#\" class=\"form__link\">Sign-in options</a></div></form></section><footer><h6>Privacy Policy | Terms of Service</h6><h6>© 2025, Company. All Rights Reserved.</h6></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
